const actionTypes = {
    LOGIN_STARTED: 'LOGIN_STARTED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    REGISTER_STARTED: 'REGISTER_STARTED',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILED: 'REGISTER_FAILED',
    GET_LIST_JOB_STARTED: 'GET_LIST_JOB_STARTED',
    GET_LIST_JOB_SUCCESS: 'GET_LIST_JOB_SUCCESS',
    GET_LIST_JOB_FAILED: 'GET_LIST_JOB_FAILED',
    GET_LIST_TOPIC_STARTED: 'GET_LIST_TOPIC_STARTED',
    GET_LIST_TOPIC_SUCCESS: 'GET_LIST_TOPIC_SUCCESS',
    GET_LIST_TOPIC_FAILED: 'GET_LIST_TOPIC_FAILED',
}

export default actionTypes