import Head from 'next/head'
import { useState } from 'react'
import LayoutAuth from '@/containers/LayoutAuth'
import {
    H1,
    H2,
    Space
} from '../components/Typography/index'
import {
    InputEmail,
    InputPassword,
    InputText,
    FButton
} from '../components/form/index'
import { Hyperlink } from '@/components'

export default function Forget() {
    const [formValue, setFormValue] = useState({})
    const handleSubmit = (event) => {
        if (event) event.preventDefault()
        console.log('handle submited!', formValue)
    }
    const handleOnChange = (name, value) => {
      setFormValue({
          ...formValue,
          [name]: value,
        })
    }
  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LayoutAuth>
            <H2>Login Page</H2>
            <form onSubmit={handleSubmit}>
                <InputEmail onChange={(value => handleOnChange('email', value))} placeholder='Email'/>
                <Space/>
                <InputPassword onChange={(value => handleOnChange('password', value))}placeholder='Password'/>
                <Space/>
                <FButton type='submit'>Send</FButton>
                <div>
                  <Hyperlink href='/signup'>
                    Sign Up
                  </Hyperlink>
                  <br/>
                  <Hyperlink href='/forgot'>
                    Forget Password!
                  </Hyperlink>
                </div>
            </form>
        </LayoutAuth>
      </main>
    </>
  )
}
