import React from 'react'
import { css } from '@emotion/css'
import HomePageBanner from '@/containers/HomePageBanner/HomePageBanner'
import LayoutPage from '@/containers/LayoutPage'
import Layout from '@/containers/Layout'
import Link from 'next/link'
import Head from 'next/head'
import { H1, H2, Space } from '@/components'
import JobCardList from '@/containers/jobCardList/jobCardList'
import { GET_LIST_TOPIC_ACTION } from '@/actions'
import { Hyperlink } from '@/components'

const Home = ({ topics, loading }) => {
  console.log(topics, loading)
  return (
      <div>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <H1 className={css`text-transform:uppercase;`}>
        become a better version of yourself 
        </H1>
        <Hyperlink href={'/contact'}>Contact</Hyperlink>
        <Space/>
        <Hyperlink href={'/about'}>About</Hyperlink>
        </Layout>
      <div className={css`
      display:flex;
      justify-content:center;
      align-items:center;
      width:100vw;
      margin-bottom: 15px;
      `}>
      <img className={css`border-radius:20px;
      width: 100px;
      `} src='7644688.png'/>
      </div>
      <LayoutPage>
        <HomePageBanner/>
        <div
          className={css`
            display: flex;
            max-width: 1000px;
            padding: 32px 0;
            margin: 0 auto;
            flex-direction: column;
          `}
        >
          <H2
            className={css`
              padding-bottom: 32px;
            `}
          >
            -- Here we go --
          </H2>
          <div>
            <JobCardList topics={topics} loading={loading} />
          </div>
        </div>
      </LayoutPage>
      </div>
  )
}
/*
Home.getInitialProps = async ({ reduxStore }) => {
  await reduxStore.dispatch(GET_LIST_TOPIC_ACTION())
  const { job } = await reduxStore.getState()
  return {
    loading: job.loading,
    jobs: job.jobs,
  }
}
*/
Home.getInitialProps = async ({ reduxStore }) => {
  await reduxStore.dispatch(GET_LIST_TOPIC_ACTION())
  const { topic } = await reduxStore.getState()
  return {
    loading: topic.loading,
    topics: topic.topics,
  }
}
export default Home


























/*
import Head from 'next/head'
import Link from 'next/link'
import Layout from '../containers/Layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
        <h1>
          welcome to home page
        </h1>
        <Link href={'/about'}>
          About US
        </Link>
        </Layout>
      </main>
    </>
  )
}

/*
import { css } from '@emotion/css'
import Head from 'next/head'
import LayoutPage from '../containers/LayoutPage'
import HomePageBanner from '../containers/HomePageBanner/HomePageBanner'
import { GET_LIST_JOB_ACTION } from '../actions'
import { H2 } from '@/components'
import JobCardList from '@/containers/jobCardList/jobCardList'

const Home = ({ jobs, loading }) => {
  return (
    <div className="container">
      <Head>
        <title>home</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutPage>
        <HomePageBanner />
        <div
          className={css`
            display: flex;
            max-width: 1000px;
            padding: 32px 0;
            margin: 0 auto;
            flex-direction: column;
          `}
        >
          <H2
            className={css`
              padding-bottom: 32px;
            `}
          >
            H2
          </H2>
          <div>
            <JobCardList jobs={jobs} loading={loading} />
          </div>
        </div>
      </LayoutPage>
    </div>
  )
}

Home.getInitialProps = async ({ reduxStore }) => {
  await reduxStore.dispatch(GET_LIST_JOB_ACTION())
  const { job } = await reduxStore.getState()
  return {
    loading: job.loading,
    jobs: job.jobs,
  }
}
export default Home
*/
