import Head from 'next/head'
import { useEffect, useState } from 'react'
import LayoutAuth from '@/containers/LayoutAuth'
import {
    H1,
    H2,
    Space
} from '../components/Typography/index'
import {
    InputEmail,
    InputPassword,
    InputText,
    FButton
} from '../components/form/index'
import { Hyperlink } from '@/components'
import { REGISTER_ACTION } from '@/actions'
import { useDispatch, useSelector } from 'react-redux'
import { useRouter } from 'next/router'

export default function Signup() {
    const dispatch = useDispatch()
    const [formValue, setFormValue] = useState({})
    const router = useRouter()
    const auth = useSelector((state) => state.auth)

    const handleSubmit = (event) => {
        if (event) event.preventDefault()
        console.log('handle submited!', formValue)
        dispatch(REGISTER_ACTION(formValue))
    }
    const handleOnChange = (name, value) => {
      setFormValue({
          ...formValue,
          [name]: value,
        })
    }

    useEffect(() => {
      if (
        auth.response &&
        auth.response.user &&
        auth.response.user.access_token
      ) {
        router.push('/login')
      }
    })
  return (
    <>
      <Head>
        <title>Signup Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LayoutAuth>
            <H2>Please Signup</H2>
            <form onSubmit={handleSubmit}>
                <InputText onChange={(value => handleOnChange('text', value))} placeholder='Text'/>
                <Space/>
                <InputEmail onChange={(value => handleOnChange('email', value))} placeholder='Email'/>
                <Space/>
                <InputPassword onChange={(value => handleOnChange('password', value))}placeholder='Password'/>
                <Space/>
                <FButton type='submit' loading={auth.loading}>SignUp</FButton>
                <div>
                  <Hyperlink href='/login'>
                    Login
                  </Hyperlink>
                </div>
            </form>
        </LayoutAuth>
      </main>
    </>
  )
}
